### ISSUE TITLE
Target sequence length > 100K,  over comparison pipeline limit.

### ISSUE THREAD

**Issue by sgirald** [chrisjackson-pellicle/NewTargets#2]
Hello¡
I tried to add sequences from this transcriptome (https://www.ncbi.nlm.nih.gov/data-hub/genome/GCA_025175665.1/) to the angiosperms353 target file.

The script was working well: 
353 alignments generated from 353 fasta files.
353 HMM profiles generated from 353 alignment files. 

Once I got to this step:  Searching transcriptomes with HMM profiles...  the next error occurred:

Fatal exception (source file p7_pipeline.c, line 697): Target sequence length > 100K, over comparison pipeline limit. (Did you mean to use nhmmer/nhmmscan?) 

I've checked the angiosperms353target.fasta and all sequences are < 100K. In contrast, in the transcriptome.fasta most of the individual sequences are > 100K. So, I guess the error "Target sequence length > 100K...." is making reference to the transcriptome sequences.

This made me think one solution could be Splitting the Genbank transcriptome file into smaller sequences?

Any suggestion on how to solve this issue? 
thank you

**Comment by chrisjackson-pellicle** [comment]
Hi @sgirald,

The data you linked to is a genome assembly rather than a transcriptome. Did you mean to provide a different link?

Cheers,

Chris

**Comment by sgirald** [comment]
hi @chrisjackson-pellicle, 

You were right. I supplied the wrong link and was using the wrong file.  Sorry

**Comment by chrisjackson-pellicle** [comment]
No worries!
