### ISSUE TITLE
BYO_transcriptomes_renamed.fasta

### ISSUE THREAD

**Issue by sgirald** [chrisjackson-pellicle/NewTargets#3]
Hi, 

When trying to add sequences from mytranscriptome.fasta to the Angiosperms353_target.fasta using the BYO_transcriptome.py, I got multiple errors, which seem to be linked to a file called BYO_transcriptomes_renamed.fasta

It seems BYO_transcriptome.py correctly generates the file mytranscriptome_renamed.fasta, but then tries to use an empty file called BYO_transcriptomes_renamed.fasta

The only way I managed to make BYO_transcriptome.py work without any error messages was by renaming my transcriptome (from mytranscriptome.fasta to BYO_transcriptomes.fasta)

Any feedback would be appreciated. Thank you

**Comment by chrisjackson-pellicle** [comment]
Hi @sgirald,

I just tested `BYO_transcriptome.py` and it seems to be working fine. To confirm, you have your `mytranscriptome.fasta` file in a folder (e.g. `my_transcriptomes`), and you provide that folder to `BYO_transcriptome.py` via e.g. 

```
python BYO_transcriptome.py Angiosperms353_target.fasta.fasta my_transcriptomes -python_threads 2 -external_program_threads 5
```

Cheers,

Chris

**Comment by sgirald** [comment]
Hi @chrisjackson-pellicle , 

Thank you for your answer. Yes, I'm working in an HPC cluster and I ran the script exactly as you just indicated. Still, it only worked properly when my transcriptome was named BYO_transcriptomes.fasta

Thanks
